// const sampleListings = [
//   {
//     title: "Cozy Beachfront Cottage",
//     description:
//       "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1500,
//     location: "Malibu",
//     country: "United States",
//     coordinates: [-118.7798, 34.0259],
//   },
//   {
//     title: "Modern Loft in Downtown",
//     description:
//       "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1200,
//     location: "New York City",
//     country: "United States",
//     coordinates: [-74.006, 40.7128],
//   },
//   {
//     title: "Mountain Retreat",
//     description:
//       "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1000,
//     location: "Aspen",
//     country: "United States",
//     coordinates: [-106.8175, 39.1911],
//   },
//   {
//     title: "Historic Villa in Tuscany",
//     description:
//       "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2500,
//     location: "Florence",
//     country: "Italy",
//     coordinates: [11.2558, 43.7696],
//   },
//   {
//     title: "Secluded Treehouse Getaway",
//     description:
//       "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 800,
//     location: "Portland",
//     country: "United States",
//     coordinates: [-122.6765, 45.5231],
//   },
//   {
//     title: "Beachfront Paradise",
//     description:
//       "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2000,
//     location: "Cancun",
//     country: "Mexico",
//     coordinates: [-86.8515, 21.1619],
//   },
//   {
//     title: "Rustic Cabin by the Lake",
//     description:
//       "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 900,
//     location: "Lake Tahoe",
//     country: "United States",
//     coordinates: [-120.0324, 38.9399],
//   },
//   {
//     title: "Luxury Penthouse with City Views",
//     description:
//       "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 3500,
//     location: "Los Angeles",
//     country: "United States",
//     coordinates: [-118.2437, 34.0522],
//   },
//   {
//     title: "Ski-In/Ski-Out Chalet",
//     description:
//       "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 3000,
//     location: "Verbier",
//     country: "Switzerland",
//     coordinates: [7.2286, 46.0958],
//   },
//   {
//     title: "Safari Lodge in the Serengeti",
//     description:
//       "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 4000,
//     location: "Serengeti National Park",
//     country: "Tanzania",
//     coordinates: [34.8333, -2.3333],
//   },
//   {
//     title: "Historic Canal House",
//     description:
//       "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1800,
//     location: "Amsterdam",
//     country: "Netherlands",
//     coordinates: [4.9041, 52.3676],
//   },
//   {
//     title: "Private Island Retreat",
//     description:
//       "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bG9kZ2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 10000,
//     location: "Fiji",
//     country: "Fiji",
//     coordinates: [178.065, -17.7134],
//   },
//   {
//     title: "Charming Cottage in the Cotswolds",
//     description:
//       "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2glMjB2YWNhdGlvbnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1200,
//     location: "Cotswolds",
//     country: "United Kingdom",
//     coordinates: [-1.8433, 51.8333],
//   },
//   {
//     title: "Historic Brownstone in Boston",
//     description:
//       "Step back in time in this elegant historic brownstone located in the heart of Boston.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2200,
//     location: "Boston",
//     country: "United States",
//     coordinates: [-71.0589, 42.3601],
//   },
//   {
//     title: "Beachfront Bungalow in Bali",
//     description:
//       "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1800,
//     location: "Bali",
//     country: "Indonesia",
//     coordinates: [115.1889, -8.4095],
//   },
//   {
//     title: "Mountain View Cabin in Banff",
//     description:
//       "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1500,
//     location: "Banff",
//     country: "Canada",
//     coordinates: [-115.5708, 51.1784],
//   },
//   {
//     title: "Art Deco Apartment in Miami",
//     description:
//       "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
//     image: {
//       filename: "listingimage",
//       url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1600,
//     location: "Miami",
//     country: "United States",
//     coordinates: [-80.1918, 25.7617],
//   },
//   {
//     title: "Tropical Villa in Phuket",
//     description:
//       "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 3000,
//     location: "Phuket",
//     country: "Thailand",
//     coordinates: [98.3923, 7.8804],
//   },
//   {
//     title: "Historic Castle in Scotland",
//     description:
//       "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGJlYWNoJTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 4000,
//     location: "Scottish Highlands",
//     country: "United Kingdom",
//     coordinates: [-4.2026, 57.1207],
//   },
//   {
//     title: "Desert Oasis in Dubai",
//     description:
//       "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHViYWl8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 5000,
//     location: "Dubai",
//     country: "United Arab Emirates",
//     coordinates: [55.2708, 25.2048],
//   },
//   {
//     title: "Rustic Log Cabin in Montana",
//     description:
//       "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1100,
//     location: "Montana",
//     country: "United States",
//     coordinates: [-110.3626, 46.8797],
//   },
//   {
//     title: "Beachfront Villa in Greece",
//     description:
//       "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2500,
//     location: "Mykonos",
//     country: "Greece",
//     coordinates: [25.3289, 37.4467],
//   },
//   {
//     title: "Eco-Friendly Treehouse Retreat",
//     description:
//       "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 750,
//     location: "Costa Rica",
//     country: "Costa Rica",
//     coordinates: [-83.7534, 9.7489],
//   },
//   {
//     title: "Historic Cottage in Charleston",
//     description:
//       "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1600,
//     location: "Charleston",
//     country: "United States",
//     coordinates: [-79.9311, 32.7765],
//   },
//   {
//     title: "Modern Apartment in Tokyo",
//     description:
//       "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRva3lvfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2000,
//     location: "Tokyo",
//     country: "Japan",
//     coordinates: [139.6917, 35.6895],
//   },
//   {
//     title: "Lakefront Cabin in New Hampshire",
//     description:
//       "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1200,
//     location: "New Hampshire",
//     country: "United States",
//     coordinates: [-71.5724, 43.1939],
//   },
//   {
//     title: "Luxury Villa in the Maldives",
//     description:
//       "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 6000,
//     location: "Maldives",
//     country: "Maldives",
//     coordinates: [73.2207, 3.2028],
//   },
//   {
//     title: "Ski Chalet in Aspen",
//     description:
//       "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGxha2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 4000,
//     location: "Aspen",
//     country: "United States",
//     coordinates: [-106.8175, 39.1911],
//   },
//   {
//     title: "Secluded Beach House in Costa Rica",
//     description:
//       "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2glMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1800,
//     location: "Costa Rica",
//     country: "Costa Rica",
//     coordinates: [-84.0907, 9.9281],
//     owner: '6a36d78c6f2e1fe3768d78e5',
//   },
// ];

// module.exports = { data: sampleListings };

const sampleListings = [

  // ─── ADDITIONAL LISTINGS ───────────────────────────────────────
  {
    title: "Overwater Bungalow in Bora Bora",
    description: "Wake up above the turquoise lagoon in this iconic overwater bungalow. Snorkel directly from your private deck.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=800&q=60",
    },
    price: 7500,
    location: "Bora Bora",
    country: "French Polynesia",
    coordinates: [-151.7415, -16.5004],
    category: ["beaches", "villas", "tropical"],
  },
  {
    title: "Cliffside Villa in Santorini",
    description: "Perched on the volcanic cliffs of Santorini, this whitewashed villa offers breathtaking Aegean sunset views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=60",
    },
    price: 4200,
    location: "Santorini",
    country: "Greece",
    coordinates: [25.4615, 36.3932],
    category: ["villas", "iconic_cities", "trending"],
  },
  {
    title: "Jungle Camping in the Amazon",
    description: "Fall asleep to the sounds of the rainforest in this immersive Amazon jungle camp. Guided wildlife tours included.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=60",
    },
    price: 1400,
    location: "Manaus",
    country: "Brazil",
    coordinates: [-60.0212, -3.119],
    category: ["camping", "tropical", "countryside"],
  },
  {
    title: "Rooftop Studio in Paris",
    description: "A chic rooftop studio steps from the Eiffel Tower. Sip coffee on your private terrace with iconic Parisian views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=60",
    },
    price: 2800,
    location: "Paris",
    country: "France",
    coordinates: [2.3522, 48.8566],
    category: ["iconic_cities", "rooms", "trending"],
  },
  {
    title: "Vineyard Farmhouse in Bordeaux",
    description: "Stay in a rustic stone farmhouse surrounded by rolling vineyards. Wine tasting and cycling through the estate included.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Bordeaux",
    country: "France",
    coordinates: [-0.5792, 44.8378],
    category: ["countryside", "villas", "rooms"],
  },
  {
    title: "Ski Lodge in the Japanese Alps",
    description: "Experience world-famous powder snow in Niseko. This cozy lodge is steps from the lifts with an onsen hot spring.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Niseko",
    country: "Japan",
    coordinates: [140.6875, 42.8042],
    category: ["ski", "mountains", "rooms"],
  },
  {
    title: "Northern Lights Cabin in Norway",
    description: "Hunt the aurora borealis from this remote glass-fronted cabin on the Norwegian fjords. Pure Arctic wilderness.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=60",
    },
    price: 4100,
    location: "Tromsø",
    country: "Norway",
    coordinates: [18.9553, 69.6492],
    category: ["arctic", "countryside", "trending"],
  },
  {
    title: "Castle Hotel in Prague",
    description: "Stay in a beautifully restored baroque castle overlooking the red rooftops of Prague's Old Town.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=800&q=60",
    },
    price: 3800,
    location: "Prague",
    country: "Czech Republic",
    coordinates: [14.4378, 50.0755],
    category: ["castles", "iconic_cities", "trending"],
  },
  {
    title: "Infinity Pool Villa in Ubud",
    description: "A stunning jungle villa with a private infinity pool overlooking Bali's terraced rice paddies.",
    image: {
      filename: "listingimage",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHUIt5nPg22ClfRARESDclW8STh38lP6n6GvaIh4Q657XkHe3o0-JbuYVf&s=10",
    },
    price: 2600,
    location: "Ubud",
    country: "Indonesia",
    coordinates: [115.2624, -8.5069],
    category: ["pools", "villas", "tropical"],
  },
  {
    title: "Converted Barn in Tuscany",
    description: "A lovingly converted stone barn in the Tuscan hills. Olive groves, sunflower fields and total tranquility.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=800&q=60",
    },
    price: 1900,
    location: "Siena",
    country: "Italy",
    coordinates: [11.3308, 43.3186],
    category: ["countryside", "rooms", "villas"],
  },
  {
    title: "Beachside Camping in Goa",
    description: "Fall asleep to crashing waves in a premium beach camp on North Goa's most scenic stretch of coastline.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1510672981848-a1c4f1cb5ccf?auto=format&fit=crop&w=800&q=60",
    },
    price: 600,
    location: "Goa",
    country: "India",
    coordinates: [73.8278, 15.4909],
    category: ["camping", "beaches", "tropical"],
  },
  {
    title: "Lakeside Dome in Patagonia",
    description: "A futuristic transparent dome on the edge of a glacial lake in Chilean Patagonia. Condors fly past at breakfast.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=60",
    },
    price: 3600,
    location: "Torres del Paine",
    country: "Chile",
    coordinates: [-72.9303, -51.0],
    category: ["domes", "mountains", "camping"],
  },
  {
    title: "Sahara Desert Camp in Morocco",
    description: "Spend the night under a billion stars in a luxury Bedouin camp deep in the Sahara dunes of Merzouga.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=800&q=60",
    },
    price: 2100,
    location: "Merzouga",
    country: "Morocco",
    coordinates: [-4.0124, 31.0998],
    category: ["camping", "countryside", "trending"],
  },
  {
    title: "Floating Villa in Bangkok",
    description: "A unique floating villa on the Chao Phraya River with panoramic views of Bangkok's glittering skyline.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=60",
    },
    price: 2400,
    location: "Bangkok",
    country: "Thailand",
    coordinates: [100.5018, 13.7563],
    category: ["houseboat", "iconic_cities", "pools"],
  },
  {
    title: "Lava Cave Stay in Hawaii",
    description: "A one-of-a-kind stay inside a real lava tube on the Big Island. Ancient volcanic walls surround you.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542259009477-d625272157b7?auto=format&fit=crop&w=800&q=60",
    },
    price: 2900,
    location: "Big Island",
    country: "United States",
    coordinates: [-155.5828, 19.8968],
    category: ["caves", "tropical", "trending"],
  },
  {
    title: "Penthouse in Dubai Marina",
    description: "Ultra-luxury penthouse in Dubai Marina with floor-to-ceiling views, private rooftop pool and butler service.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=60",
    },
    price: 8000,
    location: "Dubai",
    country: "United Arab Emirates",
    coordinates: [55.1406, 25.0805],
    category: ["iconic_cities", "pools", "rooms"],
  },
  {
    title: "Treehouse Resort in Wayanad",
    description: "Perched high in the rainforest canopy of Wayanad, this treehouse offers misty mornings and wildlife sightings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1440581572325-0bea30efa8a0?auto=format&fit=crop&w=800&q=60",
    },
    price: 950,
    location: "Wayanad",
    country: "India",
    coordinates: [76.0521, 11.6854],
    category: ["tropical", "camping", "countryside"],
  },
  {
    title: "Ice Hotel in Swedish Lapland",
    description: "Sleep on a bed carved from ice in this legendary ice hotel rebuilt every winter in the Arctic wilderness of Sweden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1547234935-80c7145ec969?auto=format&fit=crop&w=800&q=60",
    },
    price: 5200,
    location: "Jukkasjärvi",
    country: "Sweden",
    coordinates: [20.6051, 67.8558],
    category: ["arctic", "caves", "trending"],
  },

  // ─── EXISTING LISTINGS (updated) ───────────────────────────────
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    coordinates: [-118.7798, 34.0259],
    category: ["beaches", "rooms", "trending"],
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    coordinates: [-74.006, 40.7128],
    category: ["iconic_cities", "rooms", "trending"],
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    coordinates: [-106.8175, 39.1911],
    category: ["mountains", "camping", "countryside"],
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    coordinates: [11.2558, 43.7696],
    category: ["villas", "countryside", "trending"],
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    coordinates: [-122.6765, 45.5231],
    category: ["camping", "tropical", "countryside"],
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    coordinates: [-86.8515, 21.1619],
    category: ["beaches", "pools", "tropical"],
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    coordinates: [-120.0324, 38.9399],
    category: ["mountains", "camping", "countryside"],
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    coordinates: [-118.2437, 34.0522],
    category: ["iconic_cities", "rooms", "pools"],
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    coordinates: [7.2286, 46.0958],
    category: ["ski", "mountains", "trending"],
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    coordinates: [34.8333, -2.3333],
    category: ["camping", "countryside", "trending"],
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    coordinates: [4.9041, 52.3676],
    category: ["iconic_cities", "houseboat", "rooms"],
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    coordinates: [178.065, -17.7134],
    category: ["beaches", "villas", "tropical"],
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
    coordinates: [-1.8433, 51.8333],
    category: ["countryside", "rooms", "trending"],
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Boston",
    country: "United States",
    coordinates: [-71.0589, 42.3601],
    category: ["iconic_cities", "rooms"],
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Bali",
    country: "Indonesia",
    coordinates: [115.1889, -8.4095],
    category: ["beaches", "pools", "tropical"],
  },
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Banff",
    country: "Canada",
    coordinates: [-115.5708, 51.1784],
    category: ["mountains", "ski", "camping"],
  },
  {
    title: "Art Deco Apartment in Miami",
    description: "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Miami",
    country: "United States",
    coordinates: [-80.1918, 25.7617],
    category: ["iconic_cities", "beaches", "rooms"],
  },
  {
    title: "Tropical Villa in Phuket",
    description: "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Phuket",
    country: "Thailand",
    coordinates: [98.3923, 7.8804],
    category: ["tropical", "villas", "pools"],
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    coordinates: [-4.2026, 57.1207],
    category: ["castles", "countryside", "trending"],
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 5000,
    location: "Dubai",
    country: "United Arab Emirates",
    coordinates: [55.2708, 25.2048],
    category: ["iconic_cities", "pools", "villas"],
  },
  {
    title: "Rustic Log Cabin in Montana",
    description: "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1100,
    location: "Montana",
    country: "United States",
    coordinates: [-110.3626, 46.8797],
    category: ["countryside", "camping", "mountains"],
  },
  {
    title: "Beachfront Villa in Greece",
    description: "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Mykonos",
    country: "Greece",
    coordinates: [25.3289, 37.4467],
    category: ["beaches", "villas", "trending"],
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description: "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 750,
    location: "Costa Rica",
    country: "Costa Rica",
    coordinates: [-83.7534, 9.7489],
    category: ["tropical", "camping", "countryside"],
  },
  {
    title: "Historic Cottage in Charleston",
    description: "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Charleston",
    country: "United States",
    coordinates: [-79.9311, 32.7765],
    category: ["rooms", "countryside"],
  },
  {
    title: "Modern Apartment in Tokyo",
    description: "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Tokyo",
    country: "Japan",
    coordinates: [139.6917, 35.6895],
    category: ["iconic_cities", "rooms", "trending"],
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description: "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New Hampshire",
    country: "United States",
    coordinates: [-71.5724, 43.1939],
    category: ["mountains", "camping", "countryside"],
  },
  {
    title: "Luxury Villa in the Maldives",
    description: "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 6000,
    location: "Maldives",
    country: "Maldives",
    coordinates: [73.2207, 3.2028],
    category: ["villas", "beaches", "tropical"],
  },
  {
    title: "Ski Chalet in Aspen",
    description: "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Aspen",
    country: "United States",
    coordinates: [-106.8175, 39.1911],
    category: ["ski", "mountains", "villas"],
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description: "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Costa Rica",
    country: "Costa Rica",
    coordinates: [-84.0907, 9.9281],
    category: ["beaches", "tropical", "camping"],
  },

  // ─── NEW LISTINGS (filling gaps) ───────────────────────────────
  {
    title: "Floating Houseboat in Kerala",
    description: "Drift through the serene backwaters of Kerala on this traditional houseboat. Wake up to misty canals and lush greenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Alleppey",
    country: "India",
    coordinates: [76.3388, 9.4981],
    category: ["houseboat", "tropical", "trending"],
  },
  {
    title: "Houseboat on Dal Lake",
    description: "Enjoy the timeless charm of a hand-carved wooden houseboat on the legendary Dal Lake in Kashmir.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Srinagar",
    country: "India",
    coordinates: [74.7973, 34.0837],
    category: ["houseboat", "mountains", "rooms"],
  },
  {
    title: "Ice Cave Lodge in Iceland",
    description: "Sleep inside a glacier in this extraordinary ice cave lodge. Northern lights visible right from your bed.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=60",
    },
    price: 5500,
    location: "Vatnajökull",
    country: "Iceland",
    coordinates: [-16.9767, 64.4115],
    category: ["caves", "arctic", "trending"],
  },
  {
    title: "Underground Cave Suite in Cappadocia",
    description: "Carved into ancient volcanic rock, this cave suite offers a truly one-of-a-kind stay with stunning valley views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Göreme",
    country: "Turkey",
    coordinates: [34.8289, 38.6431],
    category: ["caves", "domes", "trending"],
  },
  {
    title: "Geodesic Dome in the Scottish Highlands",
    description: "Stargaze through your transparent dome roof in this cozy glamping pod set against dramatic Highland scenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=60",
    },
    price: 1900,
    location: "Inverness",
    country: "United Kingdom",
    coordinates: [-4.2247, 57.4778],
    category: ["domes", "countryside", "camping"],
  },
  {
    title: "Bubble Dome in the French Alps",
    description: "Spend the night in a transparent bubble dome surrounded by pine forests and snowy peaks — pure magic.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
    },
    price: 2800,
    location: "Chamonix",
    country: "France",
    coordinates: [6.8696, 45.9237],
    category: ["domes", "mountains", "ski"],
  },
  {
    title: "Arctic Glass Cabin in Finland",
    description: "Watch the aurora borealis dance overhead from the warmth of your glass-roofed Arctic cabin in Finnish Lapland.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520769945061-0a448c463865?auto=format&fit=crop&w=800&q=60",
    },
    price: 4800,
    location: "Saariselkä",
    country: "Finland",
    coordinates: [27.4233, 68.4206],
    category: ["arctic", "domes", "trending"],
  },
  {
    title: "Medieval Castle Stay in Loire Valley",
    description: "Sleep in a real medieval castle surrounded by vineyards and moats in France's enchanting Loire Valley.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1543429257-3eb0b9c2f7e4?auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    location: "Loire Valley",
    country: "France",
    coordinates: [0.6848, 47.3941],
    category: ["castles", "countryside", "villas"],
  },
  {
    title: "Rooftop Pool Suite in Singapore",
    description: "Enjoy an iconic infinity pool experience 57 floors above Singapore's glittering skyline.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=60",
    },
    price: 4500,
    location: "Singapore",
    country: "Singapore",
    coordinates: [103.8198, 1.3521],
    category: ["pools", "iconic_cities", "trending"],
  },
  {
    title: "Snowy Wilderness Camp in Alaska",
    description: "Experience true Arctic wilderness in a heated expedition tent camp. Dog sledding and glacier hikes await.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=800&q=60",
    },
    price: 3800,
    location: "Denali",
    country: "United States",
    coordinates: [-150.5, 63.1148],
    category: ["arctic", "camping", "mountains"],
  },
];

module.exports = { data: sampleListings };